---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  - name: windows-10-ltsb-x64
    os_type: windows

transport:
username: vagrant
password: vagrant


suites:
  - name: default
    run_list:
      - recipe[cb_windows_10_kiosk::default]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
